### ISSUE TITLE
Add it to npm and bower repositories

### ISSUE THREAD

**Issue by feimosi** [lugolabs/circles#30]
Would be great to be able to download the plugin directly to my project.

**Comment by mauron85** [comment]
+1

**Comment by mauron85** [comment]
It is now possible to publish to npm with PR https://github.com/lugolabs/circles/pull/37 and https://github.com/lugolabs/circles/pull/38

In fact it's matter of executing.

```npm publish```

But be aware that package name circles is already taken.

**Comment by feimosi** [comment]
Good job @mauron85.
@rtsinani do you plan to maintain this project? Because for a very long time it still doesn't have a stable version. IMHO it has a great potential though.

**Comment by rtsinani** [comment]
Thank you guys for your contributions; it's amazing how a 150 line script has grown. My vision for this was to be simple and do only one thing (draw a couple of circles with a number in the middle). I'd like to still maintain the project, as I still think it still does that, but in much more flexible way than two years ago. 

@feimosi I'd love to hear your ideas.

**Comment by feimosi** [comment]
I don't have any particular ideas yet, but it'd be nice if you could test it carefully and release a 1.0.0 version. I'll report any issues found during the usage on my projects.
