### ISSUE TITLE
Passing values as data attributes

### ISSUE THREAD

**Issue by atmediauk** [lugolabs/circles#42]
Great plugin. More of an enhancement but would it possible to pass values as data attributes on the div instead of in the js?

```
<div class="circle" id="circles-1" data-value="10"></div>
```

**Comment by vorbe** [comment]
Try this (obviously change variable names to and your id suite).

`				e = $("#circles-2").attr("data-value"),
				T = Circles.create({
  id:                  'circles-2',
  radius:              60,
  value:               e,
  maxValue:            100,
  width:               16,
    text: function(e) {
            return e + "<span>%</span>"
        },
	colors: ["rgba(255, 255, 255, 0.60)", "#fff"],
	duration:            600,
  wrpClass:            'circles-wrp',
  textClass:           'circles-text',
  valueStrokeClass:    'circles-valueStroke',
  maxValueStrokeClass: 'circles-maxValueStroke',
  styleWrapper:        true,
  styleText:           true
});`

And you HTML would be:
`<div class="circles" id="circles-2" data-value="12"></div>`
