### ISSUE TITLE
0 value shows a slight tick of color

### ISSUE THREAD

**Issue by corbanbrook** [lugolabs/circles#43]
Would it be possible to remove this tick of color when the value is 0?
Perhaps an option to show it or not?

![screen shot 2016-01-26 at 11 30 40 am](https://cloud.githubusercontent.com/assets/62406/12586949/5abecc4e-c420-11e5-85eb-de586b078290.png)

**Comment by rtsinani** [comment]
It should work if you specify a negative value, e.g. -1.

**Comment by ViRuSTriNiTy** [comment]
confirmed, -1 works.
