### ISSUE TITLE
Stopping the animation

### ISSUE THREAD

**Issue by rishabh0304** [lugolabs/circles#45]
Hey,
Pretty nice plugin, I am currently facing only one issue. 
Can you please tell me how to stop animation by calling a javascript function. I was using it for file upload function where the upload percent value I get through ajax but the speed of getting values is so high the sometime last update command overwrites the new one.

**Comment by rtsinani** [comment]
At the moment you can't stop the animation, but you can add small increments to the value to perform as a progress bar. View [this](https://github.com/lugolabs/circles/blob/master/spec/index.html) for an example.
