### ISSUE TITLE
add git tags for later versions

### ISSUE THREAD

**Issue by maruilian11** [lugolabs/circles#50]
hi, I'm from cdnjs. Recently we want to add your lib to https://cdnjs.com, could you please consider adding git tags for v0.0.6 and each released version in the future because we use **git auto-update** to add each released version to cdnjs automatically, it can help us maintain your lib the latest version to your lib users.
thank you very much!

https://github.com/cdnjs/cdnjs/issues/9024

**Comment by rtsinani** [comment]
@maruilian11 Will do, thank you for adding it!
