### ISSUE TITLE
Remove the Decimals

### ISSUE THREAD

**Issue by hendrikeng** [lugolabs/circles#53]
Everything works great so far , i just can't figure out how to remove the decimals that will be displayed when the Value counts up..thanks a lot 👍

**Comment by mark-chief** [comment]
How do you remove the decimals then?

**Comment by rtsinani** [comment]
@mark-chief You can specify `value` option as integer, as in the [circle.html](https://github.com/lugolabs/circles/blob/master/spec/circle.html) example.

**Comment by MarcoGiorgi** [comment]
@rtsinani that's wrong. If you read carefully the @hendrikeng comment he clearly specifies "when the Value counts up", that means the decimal values that appear when the numbers are spinning, during the "loading".
It's not enough to specify an integer value, you can reproduce the issue by inserting 80 as max-value and 40 as value, with a loading duration of 2000 milliseconds. You'll see the decimals appear.
