### ISSUE TITLE
Shape on the end of the stroke

### ISSUE THREAD

**Issue by justinmz** [lugolabs/circles#54]
Hi,

This is more of a feature request, just want to know if it's possible to add a shape in front of the stroke. In my case I need to add a dot/circular shape to it e.g. 
![circle](https://user-images.githubusercontent.com/2512996/30201876-9313701c-947c-11e7-99f4-1ba3b0ee8433.png)
. I could see a case of someone needing an arrow on the end maybe.

**Comment by rtsinani** [comment]
Great idea, but it could open a whole discussion, which I think it's a bit outside the scope of Circles.
