### ISSUE TITLE
Documentation needs to be more clear 

### ISSUE THREAD

**Issue by mandajoan** [lugolabs/circles#56]
I am looking to make circles work within my React.js app as my UX Designer has used in in her code. I am familiar with Highcharts and am assuming since you explain Circles is based on that approach, I can incorporate it into React the same way. But I do have some feedback on your documentation:

- It says you can install via npm but does not link to the npm package page or give the exact name of the package to install:
   

From the Documentation:

> > Install with grunt
> Get the library
> Install all the dependencies, run npm install
> Once you have the dependencies installed, run grunt from the project directory. This will run the default grunt task which will minify circles.js to circles.min.js
> 

I couldn't find a reference to it in the PR records either, though there is a trail of when it was added back in 2015 

- There is no example of how to use Circles with React/Angular/Vue/etc and I think that is unfortunate as most web developers are now progressing in these libraries/frameworks 

In the chances this 'issue' gets a response soon, I would appreciate someone sharing the exact npm package to use and if anyone has used Circles in a React app please share your approach as well. 

Thanks!

**Comment by rtsinani** [comment]
@mandajoan The reference to `npm` in the README refers to `grunt` installation of dependencies, not an actual npm package.
