### ISSUE TITLE
Feature request - background & font color

### ISSUE THREAD

**Issue by El4a** [lugolabs/circles#58]
Wouldn't it be convenient if we can change the background color of the inner circle? Now it is transparent, which is great because in most cases the background of a webpage will be white-ish. But for those times when using it in a dark theme for example, I think it would be a nice extra if you could parameterise the background and font color. I'd be happy to take a look at it if you're interested. Unless this feature already exists and I dumbly overlooked it?

**Comment by rtsinani** [comment]
@El4a Feel free to have a look. I do want to have this library as small as possible though.

**Comment by rajasimon** [comment]
Started using circles js and me too wanted this  _Workaround_
```
 .circles-text {
    color: white;
 }
```

**Comment by rtsinani** [comment]
@rajasimon @El4a You can set the background and colour of the circle by styling `circles-text` div, e.g.:

```
.circles-text {
  background: #eee;
  color: #f00;
  border-radius: 50%;
  z-index: -1;
}
```
